#! /bin/sh

# REINITIALISE
bspc rule -r *:*
killall sxhkd
sxhkd -c ~/.config/sxhkd/bspwm_bindings &
sxhkd -c ~/.config/sxhkd/application_bindings &
killall polybar
polybar -c "~/.config/polybar/config" ws &
polybar -c "~/.config/polybar/config" status &

# THEMES
get_colours () {
    FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
    BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
    GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
    YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
    BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
    MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
    CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
    WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
deploy_colours.sh
get_colours
hsetroot -solid "$BACKGROUND"
# nitrogen --restore
bspc config focused_border_color "$WHITE"
bspc config normal_border_color "$WHITE"
bspc config active_border_color "$WHITE"
bspc config presel_feedback_color "$GREEN"

# BASIC CONFIG
bspc monitor -d  1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config top_padding 34
bspc config bottom_padding 0
bspc config window_gap 5

# RULES
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Virt-manager state=floating
bspc rule -a Sxiv state=floating
